src/AppBundle/Entity/Candidate.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Candidate
 *
 * @ORM\Table(name="candidate")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CandidateRepository")
 */
class Candidate
{
	const GENDER_MALE = "M";
	const GENDER_FEMALE = "F";
	
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=1)
     * @Assert\NotBlank()
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="dateOfBirth", type="date", nullable=true)
     */
    private $dateOfBirth;

    /**
     * @var string
     *
     * @ORM\Column(name="dateOfDeath", type="date", nullable=true)
     */
    private $dateOfDeath;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Candidacy",mappedBy="candidate")
     */
    private $candidacies;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return Candidate
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return Candidate
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }
    
    public function getReverseName() {
    	return $this->getLastname()." ".$this->getFirstname();
    }
    
    public function getName() {
    	return $this->getFirstname()." ".$this->getLastname();
    }
    
    public function setGender($gender) {
    	$this->gender = $gender;
    	
    	return $this;
    }
    
    public function getGender() {
    	return $this->gender;
    }
    
    public function setDateOfBirth($dateOfBirth) {
    	$this->dateOfBirth = $dateOfBirth;
    	
    	return $this;
    }
    
    public function getDateOfBirth() {
    	return $this->dateOfBirth;
    }
    
    public function setDateOfDeath($dateOfDeath) {
    	$this->dateOfDeath = $dateOfDeath;
    	
    	return $this;
    }
    
    public function getDateOfDeath() {
    	return $this->dateOfDeath;
    }
    
    public function getCandidacies()
    {
    	return $this->candidacies;
    }
    
    public function getElections()
    {
    	$elections = array();
    	$electionsIds = array();
    	
    	foreach($this->getCandidacies() as $candidacy) {
    		
    		$election = $candidacy->getRound()->getElection();
    		
    		if(!in_array($election->getId(), $electionsIds)) {
    			
    			$electionsIds[] = $election->getId();
    			$elections[] = $election;
    		}
    	}
    	
    	return $elections;
    }
    
    public function getURLName()
    {
    	$name = "-";
    	
    	if(!empty($name)) {
    		$name = strtolower($this->getName());
    		
    		$name = str_replace("'", "", $name);
    		$name = str_replace('"', "", $name);
    		$name = str_replace("/", "", $name);
    		$name = str_replace("|", "", $name);
    		$name = str_replace('\\', "", $name);
    		$name = str_replace('?', "", $name);
    		$name = str_replace('!', "", $name);
    		$name = str_replace('(', "", $name);
    		$name = str_replace(')', "", $name);
    		$name = str_replace('°', "", $name);
    		$name = str_replace('&', "", $name);
    		$name = str_replace('§', "", $name);
    		$name = str_replace('*', "", $name);
    		$name = str_replace('%', "", $name);
    		$name = str_replace(':', "", $name);
    		$name = str_replace(',', "", $name);
    		$name = str_replace('=', "", $name);
    		$name = str_replace('+', "", $name);
    		$name = str_replace('%', "", $name);
    		$name = str_replace('.', "", $name);
    		$name = str_replace('<', "", $name);
    		$name = str_replace('>', "", $name);
    		$name = str_replace('@', "", $name);
    		$name = str_replace('#', "", $name);
    		
    		// Lowercase
    		$name = str_replace("é", "e", $name);
    		$name = str_replace("è", "e", $name);
    		$name = str_replace("ê", "e", $name);
    		$name = str_replace("ë", "e", $name);
    		$name = str_replace("â", "a", $name);
    		$name = str_replace("à", "a", $name);
    		$name = str_replace("ä", "a", $name);
    		$name = str_replace("ô", "o", $name);
    		$name = str_replace("ö", "o", $name);
    		$name = str_replace("ù", "u", $name);
    		$name = str_replace("ü", "u", $name);
    		$name = str_replace("î", "i", $name);
    		$name = str_replace("ï", "i", $name);
    		$name = str_replace("ç", "c", $name);
    		$name = str_replace("æ", "ae", $name);
    		$name = str_replace("œ", "oe", $name);

            // Uppercase
            $name = str_replace("É", "e", $name);
            $name = str_replace("È", "e", $name);
            $name = str_replace("Ê", "e", $name);
            $name = str_replace("Ë", "e", $name);
            $name = str_replace("Â", "a", $name);
            $name = str_replace("À", "a", $name);
            $name = str_replace("Ä", "a", $name);
            $name = str_replace("Ô", "o", $name);
            $name = str_replace("Ö", "o", $name);
            $name = str_replace("Ù", "u", $name);
            $name = str_replace("Ü", "u", $name);
            $name = str_replace("Î", "i", $name);
            $name = str_replace("Ï", "i", $name);
            $name = str_replace("Ç", "c", $name);
            $name = str_replace("Æ", "ae", $name);
            $name = str_replace("Œ", "oe", $name);
            
            $name = trim($name);
            
            $name = str_replace(" ", "-", $name);
    		
    		while(strpos($name, "--") !== false) {
    			 
    			$name = str_replace("--", "-", $name);
    		}
    	}
    	
    	return $name;
    }
}

src/AppBundle/Entity/City.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * City
 *
 * @ORM\Table(name="city")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CityRepository")
 */
class City
{
	const ACTUAL_COMMUNE_ACTUELLE = 1;
	const ACTUAL_COMMUNE_ASSOCIEE = 2;
	const ACTUAL_COMMUNE_PERIMEE = 3;
	const ACTUAL_ANCIEN_CODE_CHGT_DEP = 4;
	const ACTUAL_ARRONDISSEMENT_MUNICIPAL = 5;
	const ACTUAL_COMMUNE_DELEGUEE = 6;
	const ACTUAL_FRACTION_CANTONALE = 9;
	
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="actual", type="integer")
     */
    private $actual;

    /**
     * @var int
     *
     * @ORM\Column(name="cheflieu", type="integer", nullable=true)
     */
    private $cheflieu;

    /**
     * @var int
     *
     * @ORM\Column(name="cdc", type="integer", nullable=true)
     */
    private $cdc;

    /**
     * @var int
     *
     * @ORM\Column(name="rang", type="integer", nullable=true)
     */
    private $rang;

    /**
     * @var int
     *
     * @ORM\Column(name="reg", type="integer", nullable=true)
     */
    private $reg;

    /**
     * @var string
     *
     * @ORM\Column(name="dep", type="string", length=255)
     */
    private $dep;

    /**
     * @var int
     *
     * @ORM\Column(name="com", type="integer")
     */
    private $com;

    /**
     * @var int
     *
     * @ORM\Column(name="ar", type="integer", nullable=true)
     */
    private $ar;

    /**
     * @var int
     *
     * @ORM\Column(name="ct", type="integer", nullable=true)
     */
    private $ct;

    /**
     * @var int
     *
     * @ORM\Column(name="modif", type="integer")
     */
    private $modif;

    /**
     * @var string
     *
     * @ORM\Column(name="pole", type="string", length=255, nullable=true)
     */
    private $pole;

    /**
     * @var int
     *
     * @ORM\Column(name="tncc", type="integer")
     */
    private $tncc;

    /**
     * @var string
     *
     * @ORM\Column(name="artmaj", type="string", length=255, nullable=true)
     */
    private $artmaj;

    /**
     * @var string
     *
     * @ORM\Column(name="ncc", type="string", length=255)
     */
    private $ncc;

    /**
     * @var string
     *
     * @ORM\Column(name="artmin", type="string", length=255, nullable=true)
     */
    private $artmin;

    /**
     * @var string
     *
     * @ORM\Column(name="nccenr", type="string", length=255)
     */
    private $nccenr;

    /**
     * @var string
     *
     * @ORM\Column(name="articlct", type="string", length=255, nullable=true)
     */
    private $articlct;

    /**
     * @var string
     *
     * @ORM\Column(name="nccct", type="string", length=255, nullable=true)
     */
    private $nccct;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\ResultCity",mappedBy="city")
     */
    private $results;
    
    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Department",inversedBy="cities")
     * @ORM\JoinColumn(nullable=true, onDelete="CASCADE")
     */
    private $department;
    
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\DistrictCity",mappedBy="city")
     */
    private $districtsCities;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->getNccenr();
    }

    /**
     * Get full name
     *
     * @return string
     */
    public function getFullName()
    {
    	if(empty($this->getArtmin()))
        	return $this->getNccenr();
    	
		$artmin = $this->getArtmin();
		$artmin = str_replace("(", "", $artmin);
		$artmin = str_replace(")", "", $artmin);
		if(!strpos($artmin, "'") !== FALSE)// If contains "'"
			$artmin .= " ";
		
		return $artmin.$this->getName();
    }

    /**
     * Set actual
     *
     * @param integer $actual
     *
     * @return City
     */
    public function setActual($actual)
    {
        $this->actual = $actual;

        return $this;
    }

    /**
     * Get actual
     *
     * @return int
     */
    public function getActual()
    {
        return $this->actual;
    }

    /**
     * Set cheflieu
     *
     * @param integer $cheflieu
     *
     * @return City
     */
    public function setCheflieu($cheflieu)
    {
        $this->cheflieu = $cheflieu;

        return $this;
    }

    /**
     * Get cheflieu
     *
     * @return int
     */
    public function getCheflieu()
    {
        return $this->cheflieu;
    }

    /**
     * Set cdc
     *
     * @param integer $cdc
     *
     * @return City
     */
    public function setCdc($cdc)
    {
        $this->cdc = $cdc;

        return $this;
    }

    /**
     * Get cdc
     *
     * @return int
     */
    public function getCdc()
    {
        return $this->cdc;
    }

    /**
     * Set rang
     *
     * @param integer $rang
     *
     * @return City
     */
    public function setRang($rang)
    {
        $this->rang = $rang;

        return $this;
    }

    /**
     * Get rang
     *
     * @return int
     */
    public function getRang()
    {
        return $this->rang;
    }

    /**
     * Set reg
     *
     * @param integer $reg
     *
     * @return City
     */
    public function setReg($reg)
    {
        $this->reg = $reg;

        return $this;
    }

    /**
     * Get reg
     *
     * @return int
     */
    public function getReg()
    {
        return $this->reg;
    }

    /**
     * Set dep
     *
     * @param string $dep
     *
     * @return City
     */
    public function setDep($dep)
    {
        $this->dep = $dep;

        return $this;
    }

    /**
     * Get dep
     *
     * @return string
     */
    public function getDep()
    {
        return $this->dep;
    }

    /**
     * Set com
     *
     * @param integer $com
     *
     * @return City
     */
    public function setCom($com)
    {
        $this->com = $com;

        return $this;
    }

    /**
     * Get com
     *
     * @return int
     */
    public function getCom()
    {
        return $this->com;
    }

    /**
     * Set ar
     *
     * @param integer $ar
     *
     * @return City
     */
    public function setAr($ar)
    {
        $this->ar = $ar;

        return $this;
    }

    /**
     * Get ar
     *
     * @return int
     */
    public function getAr()
    {
        return $this->ar;
    }

    /**
     * Set ct
     *
     * @param integer $ct
     *
     * @return City
     */
    public function setCt($ct)
    {
        $this->ct = $ct;

        return $this;
    }

    /**
     * Get ct
     *
     * @return int
     */
    public function getCt()
    {
        return $this->ct;
    }

    /**
     * Set modif
     *
     * @param integer $modif
     *
     * @return City
     */
    public function setModif($modif)
    {
        $this->modif = $modif;

        return $this;
    }

    /**
     * Get modif
     *
     * @return int
     */
    public function getModif()
    {
        return $this->modif;
    }

    /**
     * Set pole
     *
     * @param string $pole
     *
     * @return City
     */
    public function setPole($pole)
    {
        $this->pole = $pole;

        return $this;
    }

    /**
     * Get pole
     *
     * @return string
     */
    public function getPole()
    {
        return $this->pole;
    }

    /**
     * Set tncc
     *
     * @param integer $tncc
     *
     * @return City
     */
    public function setTncc($tncc)
    {
        $this->tncc = $tncc;

        return $this;
    }

    /**
     * Get tncc
     *
     * @return int
     */
    public function getTncc()
    {
        return $this->tncc;
    }

    /**
     * Set artmaj
     *
     * @param string $artmaj
     *
     * @return City
     */
    public function setArtmaj($artmaj)
    {
        $this->artmaj = $artmaj;

        return $this;
    }

    /**
     * Get artmaj
     *
     * @return string
     */
    public function getArtmaj()
    {
        return $this->artmaj;
    }

    /**
     * Set ncc
     *
     * @param string $ncc
     *
     * @return City
     */
    public function setNcc($ncc)
    {
        $this->ncc = $ncc;

        return $this;
    }

    /**
     * Get ncc
     *
     * @return string
     */
    public function getNcc()
    {
        return $this->ncc;
    }

    /**
     * Set artmin
     *
     * @param string $artmin
     *
     * @return City
     */
    public function setArtmin($artmin)
    {
        $this->artmin = $artmin;

        return $this;
    }

    /**
     * Get artmin
     *
     * @return string
     */
    public function getArtmin()
    {
        return $this->artmin;
    }

    /**
     * Set nccenr
     *
     * @param string $nccenr
     *
     * @return City
     */
    public function setNccenr($nccenr)
    {
        $this->nccenr = $nccenr;

        return $this;
    }

    /**
     * Get nccenr
     *
     * @return string
     */
    public function getNccenr()
    {
        return $this->nccenr;
    }

    /**
     * Set articlct
     *
     * @param string $articlct
     *
     * @return City
     */
    public function setArticlct($articlct)
    {
        $this->articlct = $articlct;

        return $this;
    }

    /**
     * Get articlct
     *
     * @return string
     */
    public function getArticlct()
    {
        return $this->articlct;
    }

    /**
     * Set nccct
     *
     * @param string $nccct
     *
     * @return City
     */
    public function setNccct($nccct)
    {
        $this->nccct = $nccct;

        return $this;
    }

    /**
     * Get nccct
     *
     * @return string
     */
    public function getNccct()
    {
        return $this->nccct;
    }

    public function getResults()
    {
    	return $this->results;
    }
    

src/AppBundle/Resources/views/Default/candidate.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{% if candidate is not null %}
	    {{ "title_app_name"|trans({"%app_name%": parent(), "%title%": candidate.name}) }}
    {% else %}
	    {{ parent() }}
    {% endif %}
{% endblock %}

{% block body %}
<div class="container">
	<ol class="breadcrumb">
		<li><a href="{{ url("app_homepage") }}"><span class="glyphicon glyphicon-home"></span></a></li>
		{% if candidate is null %}
			<li class="active">{{ "unknown_candidate"|trans }}</li>
		{% else %}
    		<li class="active">{{ candidate.name }}</li>
		{% endif %}
	</ol>
	
	<div class="row">
        <div class="col-md-6">
            {% if candidate is null %}
                <h3>
                    {{ "unknown_candidate"|trans }}
                </h3>
    		{% else %}
                <h3>
    		        {{ candidate.name }}
                </h3>
                {% if candidate.dateOfBirth != NULL or candidate.dateOfDeath != NULL %}
                	<p>
                		{% if candidate.dateOfBirth != NULL or candidate.dateOfDeath != NULL %}
                	        {{ "born_in"|trans({"%date%": candidate.dateOfBirth|localizeddate("long", "none", locale)}) }}
                	    {% endif %}
                		{% if candidate.dateOfDeath != NULL %}
                    		{% if candidate.dateOfBirth != NULL %}
                    	        <br/>
                    	    {% endif %}
                    	    
                	        {{ "dead_on"|trans({"%date%": candidate.dateOfDeath|localizeddate("long", "none", locale)}) }}
                	    {% endif %}
                	</p>
                {% endif %}
                <ul>
    				{% for election in candidate.elections %}
    					<li><a href="{{ url("app_election", {"id": election.id, "name": election.urlName}) }}">{{ election.name }}</a></li>
    				{% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>	
{% endblock %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}

src/AppBundle/Resources/views/Default/city.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{% if city is not null %}
	    {{ "title_app_name"|trans({"%app_name%": parent(), "%title%": city.fullName}) }}
    {% else %}
	    {{ parent() }}
    {% endif %}
{% endblock %}

{% block body %}
<div class="container">
	<ol class="breadcrumb">
		<li><a href="{{ url("app_homepage") }}"><span class="glyphicon glyphicon-home"></span></a></li>
		{% if city is null %}
			<li class="active">{{ "unknown_city"|trans }}</li>
		{% else %}
			<li><a href="{{ url("app_department", {"id": city.department.id, "name": city.department.urlName}) }}">{{ city.department.name }}</a></li>
    		<li class="active">{{ city.fullName }}</li>
		{% endif %}
	</ol>
	
	<div class="row">
        <div class="col-md-6">
            {% if city is null %}
                <h3>
                    {{ "unknown_city"|trans }}
                </h3>
    		{% else %}
                <h3>
    		        {{ city.fullName }}
                </h3>
                <ul>
    				{% for election in city.elections %}
    					<li><a href="{{ url("app_election_city", {"election_id": election.id, "city_id": city.id, "name": election.urlName~"-"~city.urlName}) }}">{{ election.name }}</a></li>
    				{% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>	
{% endblock %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
	
	<div class="alert alert-info" role="alert"><strong>Bienvenue !</strong> Les résultats des législatives 2017 sont importés progressivement. C'est normal si vous ne voyez pas tout. ;-)</div>
	
    <h2>{{ "search"|trans }}</h2>
    
    <form method="get" action="{{ url("app_search") }}">
        <p>
            <input type="text" class="form-control" placeholder="{{ "search_item"|trans }}" name="q">
        </p>
    </form>
    
    {% if round is not null %}
		<h3>{{ "election_round"|trans({"%election%": round.election.name, "%round%": ("round_"~round.roundNumber)|trans}) }}</h3>
		
		<p>
    		<center>
    			<div class="btn-group" role="group" aria-label="">
    				{% for tempRound in round.election.rounds %}
						<a type="button" class="btn btn-default {% if tempRound.id == round.id %}active{% endif %}" href="{{ url("app_homepage", {"roundNumber": tempRound.roundNumber}) }}">{{ ("round_"~tempRound.roundNumber)|trans }}</a>
					{% endfor %}
				</div>
    		</center>
		</p>
		
	{% endif %}
</div>
    
{% if round is not null %}
	<div id="mapid" style="height: 500px; margin: 0 auto"></div>
{% endif %}

{% endblock %}

{% block js %}
<script type="text/javascript">

$(function() {
    {% if round is not null %}
        // Set map
        var map = L.map('mapid').setView([47.665387356326534, 2.70263671875], 5);
        
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={{ mapbox_access_token }}', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
            id: 'mapbox.light'
        }).addTo(map);
        
        map.attributionControl.addAttribution('{{ "data_copyright"|trans }} <a href="{{ "data_source_website"|trans }}">{{ "data_source_name"|trans }}</a>');
    
        // Prevent the zoom when we scroll the webpage
        map.scrollWheelZoom.disable();
    	
    	
        // Control that shows state info on hover
        var info = L.control();
        
        info.onAdd = function (map) {
    		this._div = L.DomUtil.create('div', 'info');
    		this.update();
    		return this._div;
        };
        
        info.update = function (props) {
        	
    		var name1 = "";
    		var result1 = "";
    		var color1 = "";
    		var name2 = "";
    		var result2 = "";
    		var color2 = "";
    		var area = "";
    		
        	if(props != null) {
    	        {% for result in round.resultsDepartment %}
                    
        	        {% set departmentCode = result.department.dep %}
                    {% if departmentCode|number_format < 10 and departmentCode != "2A" and departmentCode != "2B" %}
        				{% set departmentCode = "0" ~ departmentCode %}
                    {% endif %}
                    
        			if(props.code == '{{ departmentCode }}') {
        	            {% if result.scores|length > 0 %}
        	                {% if result.votesCast > 0 %}
    	                	    {% if round.election.type.code == constant("CODE_PRES", round.election.type) %}
                					name1 = '{{ result.scores.first.candidacy.candidate.reverseName }}'
            						color1 = "{{ result.scores.first.candidacy.nuance.color }}"
        						{% else %}
                					name1 = '{{ result.scores.first.nuance.name }}'
            						color1 = "{{ result.scores.first.nuance.color }}"
        						{% endif %}
        						
            					result1 = "{{ (result.scores.first.voices*100/result.votesCast)|number_format(2) }}"
    						{% endif %}
                			
        	                {% if result.scores|length > 1 and result.votesCast > 0 %}
	                	        {% if round.election.type.code == constant("CODE_PRES", round.election.type) %}
            						name2 = '{{ result.scores[1].candidacy.candidate.reverseName }}'
        							color2 = "{{ result.scores[1].candidacy.nuance.color }}"
        						{% else %}
            						name2 = '{{ result.scores[1].nuance.name }}'
        							color2 = "{{ result.scores[1].nuance.color }}"
    						{% endif %}
    							
        						result2 = "{{ (result.scores[1].voices*100/result.votesCast)|number_format(2) }}"
        	                {% endif %}
        					area = "{{ result.department.name }}"
        	            {% endif %}
        			}
    	        {% endfor %}
    			this._div.style.color = 'black';
    			this._div.style.backgroundColor = 'grey';
    			this._div.style.padding = '0px 10px 5px 10px';
    			this._div.style.borderRadius = '0.5em';
    			this._div.style.backgroundColor = 'white';
    		}
        	else {
    			this._div.style.backgroundColor = 'transparent';
    		}
    		
    	    {% if round.resultsDepartment|length != 0 %}
    			this._div.innerHTML = (area ? "<h5>" + area + "</h5>": "") +
    			(props && name1 ?
    			'<strong style="color:' + color1 + ';">' + name1 + '</strong><strong> : ' + result1 + ' %</strong><br />' +
    			'<strong style="color:' + color2 + ';">' + name2 + '</strong> : ' + result2 + ' %'
     			: '&nbsp;');
            {% endif %}
    	};
    	
    	info.addTo(map);
    	
    	
        var district_boundary;
    
        // Set geojson shapes
        $.ajax({
            dataType: "json",
            url: "{{ asset("bundles/app/france-geojson/departements.geojson") }}",
            success: function(data) {
    
                var multipolygon = L.geoJson(data, {
                    style: style, onEachFeature: onEachFeature
                });
    
                district_boundary = multipolygon.addTo(map);
                map.fitBounds(multipolygon.getBounds());
            }
        });
    
        // Design layout features
        function onEachFeature(feature, layer) {
            layer.on({
                mouseover: highlightFeature,
                mouseout: resetHighlight,
                click: zoomToFeature
            });
        }
    
        function resetHighlight(e) {
            district_boundary.resetStyle(e.target);
            info.update();
        }
    
        function zoomToFeature(e) {
        	var whereToGo = "{{ path("app_election_department_by_code", {"election_id": round.election.id, "department_code": "XXX", "name": round.election.urlName}) }}";
            whereToGo = whereToGo.replace("XXX", e.target.feature.properties.code);
            //whereToGo = whereToGo.replace("YYY", e.target.feature.properties.nom);
            window.location.href = whereToGo;
        }
    
        function highlightFeature(e) {
            var layer = e.target;
    
            layer.setStyle({
                weight: 4,
                color: '#fff',
                dashArray: '',
                fillOpacity: 0.7
            });
    
            if (!L.Browser.ie && !L.Browser.opera) {
                layer.bringToFront();
            }
    
            info.update(layer.feature.properties);
        }
    
        function style(feature) {
    
            return {
                fillColor: getColor(feature.properties.code),
                weight: 1,
                opacity: 1,
                color: 'white',
                dashArray: '3',
                fillOpacity: 0.7
            };
        }
    
        function getColor(d) {
    
    	    {% for result in round.resultsDepartment %}
    			if(d == '{{ result.department.dep }}' || d == '0{{ result.department.dep }}') {
    	            {% if result.scores|length > 0 and result.votesCast > 0 %}
    	                {% if round.election.type.code == constant("CODE_PRES", round.election.type) %}
                    		return '{{ result.scores.first.candidacy.nuance.color }}';
                		{% else %}
                			return '{{ result.scores.first.nuance.color }}';
                		{% endif %}
                {% endif %}
                }
            {% endfor %}
        	
            {% if round.resultsDepartment|length != 0 %}
                return 'white';
            {% endif %}
        	
            return 'grey';
        }
    {% endif %}
});

</script>
{% endblock %}